### ISSUE TITLE
Access on Alexa SystemState object

### ISSUE THREAD

**Issue by philippst** [KayLerch/alexa-skills-kit-tellask-java#4]
Hi Kay,

thanks for this great library. Really love the annotation based approach. 👍

Just one small question, feature request or wish: Is there any way to access the `SystemState` object (from `AlexaInput`) within `AlexaIntentHandler`? I think that SystemState object would be the only way to get alexa DeviceId and ApiEndpoint, which are needed in order to implement the new alexa address features. 

Amzn sample implementation: https://github.com/amzn/alexa-skills-kit-java/blob/master/samples/src/main/java/address/DeviceAddressSpeechlet.java#L138

Thanks & Regards,
Philipp

**Comment by KayLerch** [comment]
Hi Philipp,
unfortunately, I had no time to incorporate recent changes made to the request payload. There's no way to access it. But the more I see this SDK is used by others like you the more get motivated spending time on this. However, feel free to make a PR :)

In my next release, I will consider an option to directly access the request payload to not be dependent on either this or the official Java SDK when it comes to new JSON fields.

Best, Kay

**Comment by KayLerch** [comment]
I will make a new release with your recent changes asap.
