### ISSUE TITLE
Class not found: index.handler

### ISSUE THREAD

**Issue by girishnair12345** [KayLerch/alexa-skills-kit-tellask-java#9]
I took the default sample and created a jar from it via Maven, uploaded it to lambda under java 8 and as soon i hit the **LaunchIntent** I get this error
```
{
  "errorMessage": "Class not found: index.handler",
  "errorType": "java.lang.ClassNotFoundException"
}
```

The conventional way was that I used to create a command line java project, install lambda sdk and something like this

```
public class ClassName implements RequestHandler<Map<String, Object>, Object> {

@Override
    public Object handleRequest(Map<String, Object> input, Context context) {
        String data = input.toString();
        return  doAction(input.toString());
    }
```

Please do guide me if I am doing something wrong here

**Comment by KayLerch** [comment]
You have to update the "Handler" reference in your Lambda in the AWS developer console. By default it is set to index.handler but for Java it should point to the class extending AlexaRequestStreamHandler (for instance https://github.com/KayLerch/alexa-skills-kit-tellask-java/blob/master/samples/calculator/src/main/java/skill/CalculationSpeechletHandler.java). The Handler reference then consists of the package + Java class name. For the calculator example it would be "skill.CalculationSpeechletHandler"

**Comment by girishnair12345** [comment]
Ok thanks
